### ISSUE TITLE
Add a Dir argument or setting for functions writing to Datastore

### ISSUE THREAD

**Issue by lmwang9527** [gregorbj/VisionEval#101]
Currently, functions writing to Datastore (hdf5.R: initDataset, setInDatastore and inputsToDatastore) use the working directory. It'd be useful if users can change the behavior through an argument or setting, for example, configure a project directory for data that is separate from code (working directory).

**Comment by bstabler** [comment]
We decided for data integrity purposes to only allow writing to one datastore in the working directory.  If you want your datastore to be in a different directory, you can specify it in the run parameters json file.
