### ISSUE TITLE
Establish long-term objectives and procedures for using dataset name registry

### ISSUE THREAD

**Issue by gregorbj** [gregorbj/VisionEval#102]
I've developed a dataset name registry for keeping track of the names of all datasets that modules add to the datastore as a result of loading inputs and calculating values to be saved. The registry is maintained in the "VENameRegistry.json" file in the "modules" directory. There are 3 new functions for interacting with the registry: "readVENameRegistry", "writeVENameRegistry", "getRegisteredGetSpecs". I developed the registry and the functions to interact with it to aid module development. I was finding it increasingly challenging to keep track of names and to write proper Get specs for datasets in the datastore. In the long run we need to think through how the name registry should be used for checking future modules and changes to improve usability. For example, I think we should be checking new modules to make sure that they don't 'step on' existing names (i.e. use an existing dataset name to store a dataset that has a different meaning).

**Comment by bstabler** [comment]
See https://github.com/gregorbj/VisionEval/blob/master/sources/modules/VENameRegistry.json

**Comment by bstabler** [comment]
It would be a good idea to update this as part of the build/release/commit process

**Comment by bstabler** [comment]
this might be a good task for the pooled funds
