### ISSUE TITLE
Large execution time disparity when RunBy is Bzone rather then Region

### ISSUE THREAD

**Issue by gregorbj** [gregorbj/VisionEval#103]
I've observed a very large execution time disparity when the RunBy specification for a module is Bzone rather than Region. For example, when I was testing a new CalculateUrbanMixUse module, I found that it took about 15 minutes to run the test when RunBy was Bzone and 13 seconds when RunBy was Region. I suspect that most of the time difference results from writing to the datastore. This needs to be resolved.

**Comment by bstabler** [comment]
See https://github.com/gregorbj/VisionEval/tree/storagetest
