### ISSUE TITLE
add VEGUI testing to Travis

### ISSUE THREAD

**Issue by bstabler** [gregorbj/VisionEval#108]

**Comment by goreaditya** [comment]
goreaditya@4ab46556bf77a04c6d75eca10d15e234d9d0ee30

This commit should implement a simple test in Travis.

**Comment by bstabler** [comment]
Next, we'll test that the GUI can run the VERPAT model, which is basically described [here](https://github.com/gregorbj/VisionEval/wiki/Getting-Started#running-the-pilot-ve-gui-to-run-pilot-ve-rpat 
)
