### ISSUE TITLE
Module data file inclusion

### ISSUE THREAD

**Issue by danfbflynn** [gregorbj/VisionEval#110]
@kristinhull -- In the Contribution Review Criteria, the current recommendation is that all source files and data be included in the contribution.  If a contributed module does not include source data, either because of file size or confidentiality, it would probably be best if

1. A minimal example data file is included so it is clear how what data structure is needed to run the module.
2. Clear instructions are provided for how to fetch large public data (for instance, daily weather data from NOAA).
3. Clear explanation is provided of why non-included data is confidential and contact information for data owners.

**Comment by bstabler** [comment]
This has been incorporated - https://github.com/gregorbj/VisionEval/wiki/Goals-and-Objectives-of-VisionEval-Model-System
