### ISSUE TITLE
Don't pass the entire model state list to a module

### ISSUE THREAD

**Issue by gregorbj** [gregorbj/VisionEval#116]
When running a module, the framework passes the contents of the model state list (contained in ModelState.Rda file) to the module function along with the datasets specified by the module. The primary use of this has been to make the 'Seed' value available to a module to use for setting the random seed. However, the model state list includes a lot of other information that modules don't need to use and including it might encourage module developers to interact other than through the API functions they should be using. I think the data that is passed should be limited to that which is absolutely necessary. At this point it only looks like the seed value is necessary.

**Comment by bstabler** [comment]
We decided this is insignificant.
