### ISSUE TITLE
Use JSON to describe module objects

### ISSUE THREAD

**Issue by gregorbj** [gregorbj/VisionEval#12]
Module object is a little too 'listy'. Could module objects be described using JSON instead of R lists. Create an R function to process and build the necessary R objects. (Ben Stabler email comment)

**Comment by gregorbj** [comment]
I suppose it could be a JSON object that is parsed, but that might not make it any easier for the developer because they would then need to write an R script which is included in the R directory of the package and a JSON file which is put in a different directory. It also adds another layer of complexity for the framework and the need for more error trapping. My proposal would just have the one file which is in the R directory which defines all of the module functions and then wraps those functions, parameters, and data specs into a module. The script is then run when the package is built. There is a formatting alternative to making modules look less 'listy' and more readable described in the latest update to the  design document.

**Comment by bstabler** [comment]
Lists seem to work fine for the time being
