### ISSUE TITLE
Should we add a DESCRIPTION attribute in 'Inp' and 'Set' specifications?

### ISSUE THREAD

**Issue by gregorbj** [gregorbj/VisionEval#122]
The dataset name registry is very useful for cataloging the datasets produces by all 'registered' modules. However, it can be difficult to understand what a dataset is just from the dataset specifications. You have to deduce what it is from the NAME, TABLE, PROHIBIT, UNITS, and ISELEMENTOF attributes. I propose adding a DESCRIPTION attribute which developers use to enter a phrase or sentence describing the nature of the dataset. For example the DESCRIPTION of the 'Income' dataset in the 'Household' table would be: 'Total annual income of all members of the household'. This attribute would be required for all 'Inp' and 'Set' specifications. It would not be required for the 'Get' specifications and would not be checked for consistency of 'Get' specifications with datastore specifications. This attribute would not need to be stored in the datastore because the dataset name registry is created from module specifications, not from attributes saved in the datastore.

**Comment by gregorbj** [comment]
Support for DESCRIPTION attribute has been added to the 'storagetest' branch. Specifications will not pass testing unless there are proper DESCRIPTION attributes. This attribute is very important because it enforces documentation of the meaning of each dataset. Because this information is part of the code and is saved in dataset attributes, it greatly improves understanding of modules, what they consume, and what they produce. All modules in the 'storagetest' branch have been modified to include DESCRIPTION attributes and have been tested.

**Comment by bstabler** [comment]
See https://github.com/gregorbj/VisionEval/tree/storagetest
