### ISSUE TITLE
Getting Started Trouble - ODOT Staff

### ISSUE THREAD

**Issue by JoshRoll** [gregorbj/VisionEval#125]
I suspect most of my issue relates to the way our information security folks make us set up our computers and how R is installed.  The comments below relate to running through the steps on the Getting Started page.

I managed to work around most of the issues so here is what i did.  

Users need to make sure their library path .libPaths() is set to a writable location, for ODOT users it should be on your personal network drive, commonly(or always?) the F:/ drive

Ensure you are running a new enough version of R, 3.3..2 or higher.  

I was not able to determine why i kept getting an error when running line:
devtools::install_bioc(c("BiocInstaller", "rhdf5"))

I received the error:
_Installation failed: SVN does not seem to be installed on your system_

This is weird because this is the error that returns in the namesCapture and shintyTree GitHub lines above if you don't have the proxy server configured properly. 

At any rate my work around is below:
source("https://bioconductor.org/biocLite.R")
biocLite("rhdf5")

Pretty minor things to work through once you figure out what the issue is, mainly, we are behind a Great Firewall of Oregon_DOT

**Comment by bstabler** [comment]
I've updated the [Getting Started](https://github.com/gregorbj/VisionEval/wiki/Getting-Started) page.
