### ISSUE TITLE
Should we split VE resources into separate repositories 

### ISSUE THREAD

**Issue by kristinhull** [gregorbj/VisionEval#129]
@lmwang9527 said it would be easier for developers to contribute using separate repositories with a link the main VisionEval/BJ repository (e.g. https://github.com/blog/2104-working-with-submodules).  This approach would be more complicated for casual users to track the various repositories.  The team decided initially to use a single repository, but will revisit this with the pooled fund owners in the future.

**Comment by mrspeel** [comment]
Perhaps the TravelWorks website could serve as the integrator for multiple repositories making it easier for borh users and developers to use.

**Comment by e-lo** [comment]
My two-cents is that `visionEval` should be an [organization](https://help.github.com/articles/about-organizations/) on GitHub and the packages all be separate repositories.  It would make it far easier to manage the branching and development of multiple packages at once.  It would also have the benefit of being able to control commit privileges by package. 

It is relatively straightforward to [install an r-package from GitHub](https://cran.r-project.org/web/packages/githubinstall/vignettes/githubinstall.html) (or you can always submit to CRAN).

Packages would be apparent b/c they would all be in the VisionEval organization but you could also easily organize them and auto-populate a jekyll-driven github pages website at `http://visioneval.github.io`

**Comment by jrawbits** [comment]
FYI, we’ve already booked the “VisionEval” organization on Github through FHWA and Volpe.  A key activity of the upcoming pooled fund will be to get establish that location as the ongoing home for VE, as Elizabeth suggests.  We’ll be talking about that task at the first TAC meeting.  Suggestions via this Issue conversation are welcome.

**Comment by lmwang9527** [comment]
Besides always having to check out and work with the whole project code base, the current set up has another drawback of losing all history of a repo (of a new module, potential any other new packages) when it is submitted to the VisionEval code base. When I commit repo cities-lab/VETravelDemandMM to gregorbj/VisionEval/source/modules/ in pull request #130, I have to discard all history of my repo. The VisionEval organization setup suggested by @e-lo and @jrawbits would solve both. 

With the organization setup solution, to help users navigate potentially many scattered repositories, it is possible to have a curated list of repos (which can be a repo itself, with its own webpage/website). Julia has done a great job in this practice, which we can probably model after: https://github.com/JuliaLang/METADATA.jl . I can see the name_registry idea that is being implemented expanded to take up this role.

**Comment by danfbflynn** [comment]
Note that the current https://visioneval.github.io/ page is just a placeholder, but can be the homepage for multiple VisionEval repositories as @e-lo suggests. I will be making some improvements to it leading up to the first TAC meeting.

**Comment by bstabler** [comment]
I like the idea of a VE organization with many repos --- framework, package 1, package 2, GUI, etc.  On top of that, we need a website to wrap the whole thing, as @danfbflynn notes, and also a software management system (issues, wiki, testing, etc.) that operates across repositories.  We decided to postpone this discussion until after the pooled funds is up and running, as noted [here](https://github.com/gregorbj/VisionEval/wiki/Project-Meeting-2017.09.28).

**Comment by bstabler** [comment]
Parallel building of framework, modules, and models (https://travis-ci.org/gregorbj/VisionEval) really helps here.

**Comment by bstabler** [comment]
As VE continues to evolve, we continue to fight the time limit for tests on Travis.  This is something to consider when we eventually discuss this topic.

**Comment by bstabler** [comment]
This looks handy, but it's not quite the issue.  We're running into the [job limit](https://docs.travis-ci.com/user/customizing-the-build/#Build-Timeouts) when running the full VEPRAT and VERSPM models.

**Comment by bstabler** [comment]
this might be a good task for the pooled funds
