### ISSUE TITLE
Add support in framework (visioneval package) for alternative datastores

### ISSUE THREAD

**Issue by gregorbj** [gregorbj/VisionEval#131]
There are risks and limitations if the framework is tied only to the HDF5 file based datastore. We don't know how the use of HDF5 will work out when all the modules of the RSPM are run. Hundreds of datasets will be created and written to in the course of a full RSPM model run. Currently the HDF5 dataset writes are slower then they should be and if the RunBy spec for a module is set to a geography that having a number of units, the run time is agonizingly slow. This may be due to problems with the programming of the initDataset and/or writeToTable function, but could be due to using HDF5 for an application that it is not best suited to. A robust alternative using R data files is needed to assure that a full model can be implemented. The framework needs to be able to switch between different datastore types based on a model run parameter. Providing this flexibility will also enable other types of datastores in the future.

**Comment by gregorbj** [comment]
Added storagetest branch which implements a R data file based datastore and enables the datastore type to be set to be HDF5 file based or R data file based using the 'DatastoreType' property of the 'run_parameters.json' definition file. If the value is "H5" then the HDF5 datastore is used. If the value is "RD" then the R data file datastore is used.

**Comment by bstabler** [comment]
See https://github.com/gregorbj/VisionEval/tree/storagetest

**Comment by bstabler** [comment]
Closing this and creating https://github.com/gregorbj/VisionEval/issues/141
