### ISSUE TITLE
Add a 'Call' module specification

### ISSUE THREAD

**Issue by gregorbj** [gregorbj/VisionEval#132]
One or more models in RSPM/GreenSTEP call other model code. For example, the AV & carsharing model calls the DVMT model at different levels of auto ownership to calculate the marginal change in household DVMT with each additional vehicle owned. This is used to compare the marginal cost of vehicle ownership per VMT with the cost using a carshare vehicle or shared autonomous vehicle. This is a new use case for modules because it requires a module to be called by another module. It is important that this be done in a way that is consistent with the framework design objectives. The approach needs to be straight forward for module developers and easy to understand for model assemblers. It should also enable substitutions for default called modules. The proposal is that an optional 'Call' specification be added to the module specifications. If the module code calls another module, then the specification is used to identify a function name that is used in the function code and the module that is assigned to the function name. For example, in the case of the AV & carsharing module the 'Call' specification would be something like: 'predictAveDvmt = VETravelDemand::CalculateHouseholdDvmt'. When the module is run (or tested), the framework will assign the called module function to the assigned function name and will merge the 'Inp' and 'Get' specifications for the called module in with the calling module specifications.  (It would not be necessary to merge the 'Set' specifications because the module is called to return a result to the calling function, not to have a result saved in the datastore.) This approach will enable module code to be called in a very simple and easily maintainable manner. It will also enable such calls to be well documented in the module registry. Furthermore, we could enable the call to be substituted when the module is run. The 'runModule' function could have an additional argument (e.g. 'SubstituteCall') which allows users to substitute a different module to be called instead of the default specified by the module. At this point, it is necessary to implement the 'Call' specification so that RSPM module development can proceed. Enabling call substitution is not necessary and can be added to the framework later.

**Comment by gregorbj** [comment]
Typo in first sentence. It should read:
One or more models in RSPM/GreenSTEP call other model code.

**Comment by gregorbj** [comment]
Here's a really straightforward way to implement this functionality:

1) The 'Call' spec is a list which assigns a modules to be called to aliases. Following is an example where one module will be called. Say you have a module 'CalculateCarServiceUse' which will call the 'CalculateHouseholdDvmt' module in the 'VETravelDemand' package. The 'Call' spec for the 'CalculateCarServiceUse' module would look like the following:
Call = 
    items(
        calcDvmt = "VETravelDemand::CalculateHouseholdDvmt"
    )

2) When the framework runs the calling module (e.g. CalculateCarServiceUse) it does 2 additional things. First, it uses the 'Get' specs for the called module (e.g. CalculateHouseholdDvmt) to create the standard module inputs list and makes that a component of the inputs list returned to the calling module with the name of the component being the module alias defined in the 'Call' spec (e.g. calcDvmt). Second, it creates a call list which contains named components in which the names are the 'Call' spec aliases (e.g. calcDvmt) and the values are the modules assigned to the aliases (e.g. VETravelDemand::CalculateHouseholdDvmt). Then when the framework runs the calling module it passes these two lists at arguments.

3) The calling module code is written to accept two arguments (input data list and the function list) rather than just the input data list. The module code then calls the called module as in the following example where 'L' is the input list and 'M' is the module function list arguments:
M$calcDvmt(L$calcDvmt)
Of course, it is likely that the the calling module will change the inputs to the called module (e.g. L$calcDvmt) prior to calling it (there wouldn't be much point otherwise). For example, the 'CalcCarServiceUse' module would change the number of cars owned by the household in order to calculate the marginal change in car use with additional car ownership. Such changes would be made by changing the respective component of L$calcDvmt before calling the module.

**Comment by jrawbits** [comment]
I’m concerned that this approach confuses implementation and interface:  I would much rather each module had an explicit interface constructed by its developer (hiding, except via installation dependencies, any specifics of its use of any called module).  Then, if its implementation depends on another existing module, simply write whatever code you need internally to load and call the other module (and prepare the necessary data sets).  Trying to automate the communication with the other module essentially confuses the relationship, makes the whole things susceptible to unnoticed changes in the sub-module interface requirements, and risks leaking too many implementation details to any eventual model developer (putting their code at risk of unnecessary brittleness).

The basic use of VisionEval should consist of two things:  developing modules (which present themselves as standalones, and over whose implementation a developer takes explicit control – “Call” is at best a convenience, and at worst a confusion) and joining modules into models.  It’s fine to have modules use other modules, but the mechanics of that should be as straightforward as possible (and as explicit as possible internally, regarding what’s used and how in the dependent module).

My two cents, and obviously, you’re free to implement as you see fit.

**Comment by gregorbj** [comment]
Here is a more well developed explanation of module calling. It includes an interface for identifying whether a module can be called and whether any modules are called.

There are two types of modules: those that are run (run modules) and those that are called (call modules). 'Run' modules are modules that are run using the 'runModule' function in a model script. When a 'run' module is run, its outputs as specified in the 'Set' specifications are saved by the framework to the datastore. In addition, a 'run' module may specify, in 'Inp' specifications, model inputs that are to be processed and saved in the datastore. In contrast, 'call' modules are designed to be called by other modules rather than run using the 'runModule' function. 'Call' modules do not specify model inputs to be processed and although 'Set' specifications are included in the module specifications list, they are not used by the framework to save outputs to the datastore. 

The framework implements 'call' modules to enable model calculations to be performed without changing the state of datastore. For example, the CarshareAV module runs needs to calculate household DVMT at different levels of auto ownership. Without call module capability, either the code for calculating household DVMT would have to be duplicated in the CarshareAV module or the CalculateHouseholdDVMT module would have to be modified based on the needs of the CarshareAV module to run and save household DVMT at different levels of car ownership. 

A module's 'Call' specification is used to identify if a module is a 'call' module. The 'Call' specification can also be used to identify the modules that the module calls. At the present time, a module that can be called may not call other modules. In other words the framework does not support nested module calls (because no use case for nested calls has been identified and because nested calls could make understanding how a model works more difficult). The call status of a module is specified as follows:
1) When there is no 'Call' specification, the module can't be called and it calls no other modules. 
2) When the value of the 'Call' specification is TRUE, then the module may be called by other modules. 
3) When the value of the 'Call' specification is a list, the list identifies the modules that are called by the module as described below

A module call is specified in the 'Call' specification list as follows:
<Alias> = "<PackageName>::<ModuleName>"
Where: 
    <Alias> is an alias for the called module.
    <PackageName> is the name of the package in which the called module is located.
    <ModuleName> is the name of the called module.
For example:
    Call = items(CalcDvmt = "VETravelDemand::CalculateHouseholdDVMT")
In this example, the module calls the 'CalculateHouseholdDVMT' module in 'VETravelDemand' package. CalcDvmt is the alias that is used to reference called module datasets and function.

The framework does the following when a module is run which calls one or more other modules. For each of the called modules it:
1) Reads the 'Get' specifications for the called module, gets the datasets from the datastore, puts them in the standard list structure, and adds to the list that will be returned to the calling module as a component having the assigned <Alias>. In the example above, the datasets would be in a component named "CalcDvmt".
2) Creates a list which holds the values of the called module functions. Each called module function is a component of the list named by the assigned <Alias>. In the example above, this function list would have one component named "CalcDvmt" which contains the value of the CalculateHouseholdDVMT function.
The passes these two lists to the calling module when it is run. Thus the function which implements the calling module must be written to accept two arguments rather than one. The calling module code can then invoke the called module function from the function list and pass it the data from the data list. Following from the example above, if the data list is called 'L' and the function list is called 'M' (M for module because F is stands for FALSE), then the CalculateHouseholdDVMT would be called as follows:
M$CalcDvmt(L$CalcDvmt). Of in cases such as the use case example described above, the module code would likely assign the values of L$CalcDvmt to another object, make appropriate changes to the values (e.g. set auto ownership to a specified value) and then invoke M$CalcDvmt with the modified object.

The interface requirements for creating and using 'call' modules is straightforward. 
- For a module developer creating a 'call' module, the interface is simple. All they need to do is write the module without any 'Inp' specifications and set the 'Call' specification equal to TRUE.
- For a module developer who uses a 'call' module the requirements are a little more complex. They need to specify the module(s) that are called in the 'Call' specification list as described above, write their module to accept standard module data and function lists, and reference the called module function and data as described above. They also need to include in module documentation regarding information required in the datastore to run the module, information about the data requirements of the called module.
- For the model assembler, there is no need to know anything about called module. Since the called module has no input requirements it does not affect input file requirements. The datastore requirements (i.e. 'Get' specifications) of the called module are combined with the calling module in the calling module documentation so that the model assember can figure out what modules need to be run before the calling module is run. The 'initializeModel' function checks that the data requirements of the called module are satisfied.

**Comment by gregorbj** [comment]
Call module has been implemented in visioneval and is used in the VEEnergyAndEmissions package. It is documented in the design document.
