### ISSUE TITLE
Potential use of framework to support other modeling systems

### ISSUE THREAD

**Issue by gregorbj** [gregorbj/VisionEval#14]
Has ODOT thought about re-writing other models (such as OSUM) to use this framework? (Ben Stabler email comment)

**Comment by mrspeel** [comment]
ODOT is moving to ABM travel models which will be the focus of our model upgrade efforts in the next few years. We are not tackling overhauls of OSUM or JEMnR models during that transition, re-evaluating needs once the ABM is in place.
