### ISSUE TITLE
Add datastore querying capabilities

### ISSUE THREAD

**Issue by gregorbj** [gregorbj/VisionEval#154]
Presently the only functionality to extract data from a datastore is the readFromTable function which reads one dataset from a datastore. A substantial amount of effort is required to read multiple datasets from multiple tables. This gets in the way of checking modules and preparing performance measures and other summaries.  The first step to developing querying capabilities is to create a function that will read multiple datasets from multiple tables. In addition, the function should support datastore references so that when model results for a scenario are split over more than one datastore, a single function call can be used to get all the desired data for the scenario.

**Comment by bstabler** [comment]
See https://github.com/gregorbj/VisionEval/blob/add_scenario/sources/modules/VEScenario/R/ScenarioResults.R
