### ISSUE TITLE
runModule runs even if data in the specification does not exist

### ISSUE THREAD

**Issue by goreaditya** [gregorbj/VisionEval#166]
The runModule processes the module specifications but does not report an error if the data in the specification is missing. 

The VERSPM run was failing the travis test because the specification file, in the github repository, for AssignTransitService module in VETransportSupply package did not contain the variable BusDvmt as one of the outputs. BusDvmt was input to the CalculateBaseRoadDvmt module in VERoadPerformance package. The runModule continued running the CalculateBaseRoadDvmt module even though the data was missing encountering an error while evaluating the expression involving the variable.

This can be resolved in one of the two ways:
- Perform `devtools::document()` every time before installing a package which creates a new/correct specification file for a module. This will increase the run time of travis test.
- Add `checkModuleSpecs()` in `runModule` definition. This will increase the run time of the modules as it will be performing checks every time a module is run.

**Comment by gregorbj** [comment]
I like the first option better than the second because model users will be using complete packages. They won't need to run devtools:document(). Maybe there is a way to automatically run devtools:document() as part of the package build process.

**Comment by goreaditya** [comment]
This issue has been resolved by commit 16a9ac4
