### ISSUE TITLE
Recommended edits to Getting Started

### ISSUE THREAD

**Issue by dflynn-volpe** [gregorbj/VisionEval#169]
I am proposing the following changes to the wiki:

- Additional required packages: `rlang`, `dotCall64` seem to be required for VELandUse (dependency of spam, which is a dependency of fields). 
- Better yet, add `dependencies = TRUE` to step 5 install.packages
- `biocLite("zlibbioc")` seems to be required
- Remove VERoadPerformance and VEReports from step 7, as these fail with error:

```
Downloading GitHub repo gregorbj/VisionEval@master
from URL https://api.github.com/repos/gregorbj/VisionEval/zipball/master
Installation failed: Does not appear to be an R package (no DESCRIPTION)
```

- Add VECommercialTravel to step 7, as this is required by VERSPM/Test1/run_model.R
- Remove duplicated VETransportSupplyUse from step 7

I can make these changes if all agree.

**Comment by bstabler** [comment]
I just added the additional dependencies.  The inconsistency for which packages to include is a versioning issue - the master branch doesn't have VEReports, but develop does for example.  We're in the process of pulling develop into master and so I just updated the Getting Started page, but then we ran into a time limitation for the test system.  We're working on fixing it and then master and the Getting Started page will be consistent.

**Comment by dflynn-volpe** [comment]
Got it. I'll test again after master is updated, closing this issue for now.

**Comment by bstabler** [comment]
@dflynn-volpe - I just pulled develop into master and so please try again and let me know if you run into any issues.  Thanks.

**Comment by bstabler** [comment]
FYI - I updated the [testing](https://github.com/gregorbj/VisionEval/wiki/Automated-Testing) documentation to include our use of Travis caches.

**Comment by dflynn-volpe** [comment]
Really slow to install modules, but seems to be working. Even downloading and running `devtools::install_local()`, still downloading the full develop branch when trying to install each module. Consider changing the location of the remote DESCRIPTION file (e.g. [here](https://github.com/gregorbj/VisionEval/blob/master/sources/modules/VESyntheticFirms/DESCRIPTION)) to master.

**Comment by bstabler** [comment]
Done, see  https://github.com/gregorbj/VisionEval/blob/master/install.R and https://github.com/gregorbj/VisionEval/wiki/Getting-Started
