### ISSUE TITLE
Enable users to specify where data inputs for module come from

### ISSUE THREAD

**Issue by gregorbj** [gregorbj/VisionEval#20]
The “checkModuleInputs()” function makes sure that the inputs (hard-coded in the module package) have all been supplied by the modeler. Couldn’t it be more flexible?  It’d be nice as a modeler to be able to supply inputs directly or generate them from another module. In the example script you sent out, for example, perhaps someone would want to allow “PropWrkEco” to be estimated from some other Marea characteristic (by a separate module).  

I’d suggest that “checkModuleInputs()” and “checkModuleDependencies()” be integrated in some way, so that the data needed by the Module can be generated through either route. The framework just needs to check that the required data will exist in the datastore before the module executes: either in the /inputs/ folder or through the “Module$Set” function of another module. (Alex Bigazzi email comment)

**Comment by gregorbj** [comment]
What I propose is to revise things so that module specified inputs are treated as the default approach for supplying specified data if those data are not supplied by another module. So the first thing the data checking procedure would do is review the "Get" and "Set" of all of the modules and build a table of what is needed by each module and what is produced in each module. This will identify any missing data. Then it will examine the "Inp" specifications to determine which ones need to be processed to produce the missing data. This will then produce the inventory of inputs that need to be processed. The framework would write messages to the log identifying where inputs are being substituted for the module defaults. 
 
For this to work, any substituted "inputs" will need to be specified in a module that meets specifications for describing "Inp", "Set", and "Get". To make it easy to users to do substitutions (say for testing or development purposes), I propose to develop a temporary module package template or some sort of wrapper function which would enable developers or super users to create a module to load substitute inputs but still has the essential components which enable the framework to do its job.

**Comment by gregorbj** [comment]
I don’t like this solution.
I agree with Alex’s identification of the problem, but I would still argue that the solution needs to be in the function call.  The user of the function needs the option to say whether they want an input to come from the input file or the existing field in the database. 
 
I could imagine a configuration where a virtual “czone” table is already calculated upstream, but the user wants to use an input czone table from envision.  Or they have an input from envision that they were using but they are interested in testing how the results from the virtual czone table (produced up-stream) look in comparison.  From an application stand point (maybe not a development stand point), this would be much easier and cleaner if the user could just change the call to the function that uses the czone table on whether they wanted czone to come from the input or the virtual table in the data store.
 
This is one example, but I am sure that there will be many.  The code doesn’t need to make the assumptions of which is right, just have a default set and have the model through errors / stop the process if the files aren’t in the correct spots, but then given the user the option to adjust those defaults for where the data is coming from in the function without having to recompile the function.  The function shouldn’t be making those assumptions of, “well, I am not seeing the data here, so I guess I will just grab it here”.  It should error unless the user has given it the specific instructions to make a change in the defaults. (Alex Bettinardi email comment)

**Comment by gregorbj** [comment]
After I wrote this, I am thinking that some of the hesitation might be that you would have to go back and update a bunch of functions instead of handle it in one spot.  I don’t think every function needs this flexibility.  But I think if Alex has a function where he would like to have that flexibility (for the user to be able to change what comes from an input file and what comes from the data store), that he should have the green light to parameterize those inputs in the function call that he believes should have the ability to be flexible.  Alex should have the function setup to the default that he is advising be used (so that the user doesn’t have to specify anything about where the inputs are supposed to come from).  But in the instructions he could show that by altering the call the user can change inputs x, y, and z from input files to the data store, if they have calculated those inputs from up-stream models. (Alex Bettinardi email comment)

**Comment by gregorbj** [comment]
Brian, I was also thinking I don’t want to create a lot of extra work for you to go back and change. 
 
How about this option. I think we can rely on the modeler to only include input files in the /input/ folder that they want used. In the framework, the “checkModuleInputs()” followed by “loadInputFile()” functions load existing input files from the /inputs/ folder. They logs the events but DO NOT return a fatal error if some are missing (because they might be supplied by another module’s “Set” command). Then, the “checkModuleDependencies()” checks for missing “Get” data and returns the fatal error if necessary inputs aren’t either already in the datastore or will be created from another module’s “Set”. 
 
This wouldn’t really require much re-coding (I think), and would provide flexibility. But it wouldn’t be included in the function call, as Alex is suggesting. 
 
Does that make sense? (Alex Bigazzi email comment)

**Comment by gregorbj** [comment]
I don't think it would be difficult to code up what I proposed. I was planning to write a higher level function which would evaluate all of the module data needs anyway and what I'm proposing would just affect how I'm writing it. 

I'll explain my proposal and rationale a bit more below, but first I want to lay out a typology of users and their knowledge and skills because this is an important consideration in the design.
1) Module Developers: These are the people who design and estimate models (or submodels) and implement them in modules that are wrapped into packages. People who are developers need to have a fairly extensive knowledge of R in order to properly use the language to estimate models, and in order to implement those models efficiently in the language. The additional knowledge they will need to write modules to meet framework specifications is small.
2) Application Developers/Super Users: These are people who write a model script which calls modules in the appropriate order. They will need to know how to read the package documentation for modules so that they can determine what modules will work together (i.e. that the outputs created by one module are suitable as inputs needed by another module, and what other scenario input files are needed. I'm envisioning that for many applications, it will not be necessary for these application developers to delve into the structure of modules, but I think they may need to develop some custom modules to act as glue between modules or to process inputs in a different way. So I think in general the application developers will need to understand the module structure and R coding enough to build these custom modules. (However, for anything other than a temporary module, they really should complete the documentation so that their module can be bona fide framework module because some day someone will need to review the documentation.)
3) Application User: These are people who run the models put together by application developers/super users - preparing inputs, "pressing go", and summarizing outputs. These people can do their work with limited knowledge about the R language or module structure.
 
In my view, the issue we're discussing is in the domain of the module developer and the application developer. Application users should not be specifying alternate input structures or substituting data that they input for outputs created by a module. They don't have the knowledge to do this without causing problems. If they do have the required knowledge, then they are a super user and are capable of being an application developer, and should be able to do things so that they don't cause problems.

In my view the basic issue that needs to be addressed is the need to be able to manage data outside of the mechanisms established by modules in existing packages, without needing to modify and recompile a package. I can think of the following general use case examples:
1. The application developer wants to use some but not all parts of a module:
1.a. They want to substitute for some of the input data specified by the module. For example, they may want to use another module to provide those data.
1.b. They may not want to use all of the outputs of a module and substitute their data for one or more of the module outputs.
2. There are no existing packages which provide the data needed to "glue together" some modules. The application developer may need to create a simple process to create the data needed as glue and put it in the datastore.
3. A module developer needs to create one or more temporary modules to provide data needed to develop and test their module.

I believe that what I'm proposing to do will satisfy these use cases with the exception that I will need to modify a bit to address 1b. It will do this and satisfy the important objective of making the framework robust against data errors. It has been a persistent problem with GreenSTEP and RSPM that a model run crashes and then it is a painstaking process to trace back the cause of the crash; and often that cause is an input data error. I designed the framework to date to rigorously check inputs so that the data required by a model module will have the correct data type and value 'range'. If not, then the error will be identified in the data checking process that occurs before any modules are run and won't show up as some inscrutable R error message. That is why I am proposing that if a super user or developer (it's not going to be an ordinary user) wants to substitute the outputs of their own module or their own inputs, that they create a module to do this. I am convinced that this can be done in a simple enough way that anyone who is competent enough to messing with custom inputs would be competent to make a module describing those inputs in a standard format.

**Comment by gregorbj** [comment]
Thanks for the very detailed response. I was thinking of most of the use cases you describe (especially 1a), and I think it helped me to see them delineated. 

I’ll throw one more use case out that you might want to consider (maybe a 1c): an application developer wants to use functions from two different modules – but the modules have some overlapping output (“Set”) values, so they need a way of “suppressing” part of the output from one or the other module. 

I am on board with what you describe. And thanks for both considering and addressing the issue I raised. (Alex Bigazzi email comment)

**Comment by jrawbits** [comment]
I would be inclined to force an abstraction layer:  the way you get an input file into the system is through a module that creates a suitable data item (or data items) in the data store.  That module will handle input data types, mapping to the framework ontology, unique file names, units, area type, etc.  Then all modules that are not importing data will always go to the data store for what they need.  That has the merit of enabling us (okay, really just Brian) to write framework support for data import and export without making individual developers do it/screw it up.  So the key point is that all data that is being manipulated internally comes from the data store, but there may be some modules whose sole role is to load and validate data into the datastore from external sources.

**Comment by mrspeel** [comment]
In addition to checkmodules() which provides checks eithin an individual file (e.g. Vector adds to 1.0), there should be checks for consistency across files (e.g., sum of pop in one file should equal sum of Dwelling units from another times HHsize from another.

**Comment by gregorbj** [comment]
I'm closing this issue for now. We can reexamine whether it is necessary after the RSPM is converted to VisionEval. This really complicates the process of modularizing model components and checking models for correctness. The current checking process in the latest development version simulates the state of the datastore as modules would run. With each table creation, input, get, and set, it checks that the operations can succeed (i.e. table exists, no attempt to create a table that already exists, requested dataset exists, dataset attributes match, etc.). In my estimation, this checking process is greatly complicated if users can bypass module specifications substitute data from other sources. Moreover, it isn't very difficult to modify a package from the source code and rebuild it. If a user wants to change inputs or outputs they can make the change(s) to package module(s) to accomplish that.
