### ISSUE TITLE
Multi-Azone, Multi-Marea Test of VE-RSPM

### ISSUE THREAD

**Issue by gregorbj** [gregorbj/VisionEval#201]
Test of VE-RSPM with datasets that have multiple Azones and Mareas have been completed. Changes were made to a few modules in the VETravelPerformance package that were failing the test. These changes were committed to the develop branch. VE-RSPM now works with multiple Azones and Mareas.

**Comment by bstabler** [comment]
Done - https://github.com/gregorbj/VisionEval/wiki/VE-State-Status
