### ISSUE TITLE
Incomplete VEGUI setup information in Getting Started

### ISSUE THREAD

**Issue by jrawbits** [gregorbj/VisionEval#208]
I'm trying to follow installation instructions for the Development branch on a Windows 10 Home machine, and I'm getting an error message when I try to start VEGUI.  There needs to be some additional information explaining how to avoid this error (or to add a requirement that, for example, VEGUI won't work on a Windows 10 Home machine).

"Error: Initialization of plan() failed, because the test future used for validation failed. The reason was: Unexpected result (of class ‘snow-try-error’ != ‘FutureResult’) retrieved for MultisessionFuture future (label = ‘future-plan-test’, expression = ‘NA’): Package 'future' is not installed on worker (r_version: 3.5.1 (2018-07-02); platform: x86_64-w64-mingw32 (64-bit); os: Windows 10 x64 build 17134; hostname: JR-LAPTOP)"

Additional details: Package 'future' is, in fact, installed.  I've combed over the dependencies very carefully.

**Comment by goreaditya** [comment]
@jrawbits Can you provide more details by supplying information produced by running command `sessionInfo()` right after the error that was produced above? This will help us investigate the better.

**Comment by landisrm** [comment]
This issue may be related to that described in the [future vignette](https://cran.r-project.org/web/packages/future/vignettes/future-4-issues.html) under "Missing packages"

**Comment by bstabler** [comment]
I just successfully ran VERPAT, VERSPM, VEGUI, and VEScenarioViewer on Windows 10 Home edition so I'm going to close this issue.  We can open a new issue later if needed.
