### ISSUE TITLE
Running VERPAT and BaseYearVERPAT fails on branch add_scenario

### ISSUE THREAD

**Issue by landisrm** [gregorbj/VisionEval#212]
Here is the stack trace.

```
[1] "2018-11-16 12:23:52 -- Starting module 'AssignVehicleFeatures' for year '2005'."
Error: value.var (Prop) not found in input
> traceback()
10: stop("value.var (", value.var, ") not found in input", call. = FALSE)
9: cast(data, formula, fun.aggregate, ..., subset = subset, fill = fill, 
       drop = drop, value.var = value.var)
8: reshape2::dcast(VehPropByAgeIncGrpType, ... ~ VehType, value.var = "Prop", 
       fill = 0)
7: calcVehicleAges(Hh_df = Hh_df[, ModelVar_], VProp = VehPropByGroups)
6: M$Func(L)
5: runModule(ModuleName = "AssignVehicleFeatures", PackageName = "VEHouseholdVehicles", 
       RunFor = "BaseYear", RunYear = Year) at run_model.R#60
4: eval(ei, envir)
3: eval(ei, envir)
2: withVisible(eval(ei, envir))
1: source("~/Git/VisionEval/sources/models/BaseYearVERPAT/run_model.R")
> 
```

**Comment by dflynn-volpe** [comment]
BaseYearVERPAT worked for me with latest commits to `add_scenario`:
![image](https://user-images.githubusercontent.com/9107903/48681039-ede57280-eb6d-11e8-9108-979f9b363581.png)

```
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
```
I didn't see a way to export the output however, clicking on a row in Output didn't provide any option for export. Is that feature yet to be implemented?

**Comment by landisrm** [comment]
Rebuilding the VEHouseholdVehicles package seems to have solved the problem.  With a fresh install of visioneval framework and modules, VERPAT and BaseYearVERPAT now seem to be working.  

@dflynn-volpe: That appears to be an old version of VEGUI.  As far as outputs are concerned, the VERPAT model currently (in the `add_scenario` branch) writes five CSV files to the `outputs` folder in the model folder (i.e., folder that contains the ModelState.Rda file and the log file).   If you click on the Outputs tab, you should see a table available for each CSV file.  Unfortunately the download button seems to be broken currently, but that will be fixed.  In any case,  you can either simply navigate to the indicated file or  copy and paste the data from the table.  
![outputs](https://user-images.githubusercontent.com/2743628/48750737-b4386880-ec4e-11e8-9060-5f4e7bdffcb1.png)
