### ISSUE TITLE
Design Doc note to limit R-Libraries 

### ISSUE THREAD

**Issue by mrspeel** [gregorbj/VisionEval#214]
With increased discussion of installation issues, there has been a suggestion that we try to get ahead and push new developers to" minimize new R-libraries, and reuse of R-libraries used by existing VE modules".  As such, I'm suggesting we include this quoted text in these wiki locations.
Does this make sense?
 
1- the [Model System Design Documentation](https://github.com/gregorbj/VisionEval/blob/master/api/model_system_design.md) (possibly Sec 3 under "Operating System Independence" bullet?) 
2- Explicitly mention Libraries in [Contributor Review Criteria](https://github.com/gregorbj/VisionEval/wiki/Contribution-Review-Criteria) #1, "Consistent with Design Specs"

**Comment by bstabler** [comment]
See https://github.com/gregorbj/VisionEval/wiki/Contribution-Review-Criteria and the upcoming commit I'm going to tag.
