### ISSUE TITLE
VisionEval Installer (and Installer-Builder) now available

### ISSUE THREAD

**Issue by jrawbits** [gregorbj/VisionEval#216]
This is not strictly an "issue" - more of an "add on".

I've created an offline build process that constructs a standalone VisionEval installer that can work on all platforms where you can install R 3.5.1.  You can look at the build process at [https://github.com/jrawbits/VisionEval-install](https://github.com/jrawbits/VisionEval-install)  (there is a pretty extensive ReadMe aimed at developers).  You can use the install builder to (1) create an independent local runtime environment to try VisionEval in a "pristine" state on your local machine, (2) package complete installers as .zip files that can be transported offline to any machine where you can install R (note that R and VisionEval can be installed without administrator privileges) -0 just unzip and configure, or (3) perform an "online" installation that draws the packages from an online VisionEval-specific repository (built by the installer-builder) , enabling VisionEval to be installed on any machine that can host R 3.5.1 and has an internet connection. For a look at what an end user would see resulting from the installer-builder, I've got a temporary home page for the  VisionEval installation at [https://visioneval.jeremyraw.com](https://visioneval.jeremyraw.com).

All of that is a work in progress, but I'm hoping to stabilize it over the next week or so.  Trying it out and giving me feedback (you can post issues in return on the VisionEval-install repository) will be much appreciated.

**Comment by bstabler** [comment]
The best place to get the installer is https://visioneval.org/category/3download.html
