### ISSUE TITLE
link to GREENSTEP AND RSPM documumentation broken

### ISSUE THREAD

**Issue by PeterVermont** [gregorbj/VisionEval#22]
The link in index.html line 250 to:

https://github.com/gregorbj/RSPM/blob/master/GreenSTEP-RSPM_Documentation_20151220.docx

looks like it needs to be updated to: 

https://github.com/gregorbj/RSPM/blob/master/Version_3.5/Documentation/GreenSTEP-RSPM_Documentation_20151220.docx****

**Comment by gregorbj** [comment]
Done
