### ISSUE TITLE
VERSPM Test2 not working?

### ISSUE THREAD

**Issue by bstabler** [gregorbj/VisionEval#229]
VERSPM test2 is not part of the test system and does not appear to work.  Is it supposed to work?  I get the following error when running it.

https://github.com/gregorbj/VisionEval/tree/develop/sources/models/VERSPM/Test2

```
> source("run_model.R")
[1] "2018-12-26 11:40:46 -- Initializing Model."
Error in simDataTransactions(AllSpecs_ls) : 
  Model run simulation has found one or more errors. The following errors must be corrected before the model may be run. Check log for details.

```

**Comment by gregorbj** [comment]
Don't run now. I'll fix.

**Comment by gregorbj** [comment]
Fixed.
