### ISSUE TITLE
Need to bypass multiprocessing if user can't enable suitable ports

### ISSUE THREAD

**Issue by jrawbits** [gregorbj/VisionEval#234]
See pull request #233.  We have to implement the hard-coded fix there to give people a fighting chance, but having a configuration switch that we could set up during installation (test to see if multiprocess can run, and fall back to sequential if it can't).

**Comment by bstabler** [comment]
Let's test as `multiprocess` and `sequential` to understand runtime differences.

**Comment by landisrm** [comment]
I added PR #240 to allow a way to specify the type of future at run time (in `run_model.R`).  This could be also implemented at installation time.
