### ISSUE TITLE
Create function to show module documentation

### ISSUE THREAD

**Issue by gregorbj** [gregorbj/VisionEval#241]
The standard approach to module documentation is to include a commented block of text at the head of the module script. This block includes special tags to note where it starts and ends and to identify where text, tables, and figures are inserted. Markdown syntax is included within the block. The documentModule("module name here") function is called at the end of the script. The function parses the script, extracts the documentation portion, strips off the leading comments to produce markdown formatted text, and then inserts any text, tables, or figures that are identified by tags. The markdown is saved to a module_docs directory along with any image files referred to in tags. 

While these module docs are included in the installed package, a user has to know where to find them in order to view them. We need to add functionality to the framework to simplify viewing the documentation. I'm thinking that the function could be used to display the documentation for a specified module or display a listing of the documentation for modules in all VE packages from which the user could choose which documentation to view. Ideally, the documentation needs to be shown in formatted form rather than text form (such as what is shown when a markdown file is opened in GitHub).

**Comment by dflynn-volpe** [comment]
A while back there was a discussion about the best way to auto-generate documentation for individual scripts, see [notes from this meeting](https://github.com/gregorbj/VisionEval/wiki/Project-Meeting-2018.04.25). Maybe now is good time to re-consider '[roxygenizing](https://cran.r-project.org/web/packages/roxygen2/vignettes/roxygen2.html)' the documentation.

More relevant to Brian's point, it would be nice to have a [vignette](http://kbroman.org/pkg_primer/pages/vignettes.html) for each module, to take advantage of features that R users may already be familiar with. This could be a way to have a simple view of documentation for a given module.

**Comment by gregorbj** [comment]
This is already done. Look at the module scripts in the ve_rspm_state branch. I developed a simple approach which includes documentation at the head of the script as a commented block of text delimined by <doc> and </doc> tags. Inside is markdown formatted text. Also there are special tags to note where text, tables, and figures are inserted. These text, tables, and figures are generated by the model estimation portion of the script and saved. The documentModule function is called at the end of the script. This parses the documentation, inserts the text, tables, and figure references. It also reads the module specifications and inserts tables documenting inputs, data retrieved from the datastore, and data produced for the datastore. Open up one of the documentation files in the inst/module_docs directory of the package and you will see what the resulting documentation looks like.

**Comment by dflynn-volpe** [comment]
Ok, great -- what about turning these inst/module_docs into vignettes? That would be a way to display the documents in a familiar way. It seems like the hard work is done, just need to add the vignette YAML at the top of each markdown file. Then a user can `browseVignettes()` for a given module.

**Comment by gregorbj** [comment]
That would work although it might be good to have a way that the user could just browse VisionEval vignettes.
