### ISSUE TITLE
document which API functions are public and private

### ISSUE THREAD

**Issue by bstabler** [gregorbj/VisionEval#25]
document which API functions are public (i.e. can be used) and which are private (not to be used, but are internal functions called by public functions)

**Comment by gregorbj** [comment]
Added summary documentation of framework functions which identifies which ones are part of the public interface and which ones are private. Functions are grouped into several categories. Each function summary includes a short description of what the function does, lists all other framework functions that are called, and identifies changes that need to be made to the function. The summary document is 'functions_summary.md' in the 'documents' directory. This summary documentation needs to be combined with other framework specifications documentation to provide full documentation of the framework for users.

**Comment by gregorbj** [comment]
Documentation needs to be revised to correspond to the latest version.

**Comment by bstabler** [comment]
closing this since we created a new issue #43 for updating the documentation
