### ISSUE TITLE
update the example list INP, GET, SET documentation with more detail

### ISSUE THREAD

**Issue by bstabler** [gregorbj/VisionEval#26]
update the example list INP, GET, SET documentation in the example package with more detail.  For example, valid TABLE names, how years are involved, NA versus “NA”, etc.  By default, SET writes a table to the current year, and this information would be helpful in the documentation as well.

**Comment by gregorbj** [comment]
Did this in the development branch.

**Comment by bstabler** [comment]
this was merged into master
