### ISSUE TITLE
SET table function is preventing outputs from being written to the current year HDF5 folder

### ISSUE THREAD

**Issue by bstabler** [gregorbj/VisionEval#27]
We need to fix a bug in the SET table function that is preventing the [SynFirms](https://github.com/RSGInc/VisionEvalSyntheticFirms) prototype from being written to the current year HDF5 folder.  It is instead being written to the Global folder.

**Comment by gregorbj** [comment]
Found the bug. It's in the "runModule" function. When an input is specified as coming from a "Global" table, the local "Year" variable is then passed with calls to the writeToTable function. This bug will be taken care of by addressing issue #31 through implementing the use of tokens to identify the table groups that will be read from and written to.

**Comment by bstabler** [comment]
excellent

**Comment by gregorbj** [comment]
This is being addressed by the approach to Issue #31. New GROUP specification is used to identify which which group in the datastore data is to be read from or written to. "runModule" function needs to be revised to use this approach.

**Comment by gregorbj** [comment]
This implemented in the latest development version. It has been tested with the latest synthetic firms modules.
