### ISSUE TITLE
GET and SET functions data checks are cumbersome

### ISSUE THREAD

**Issue by bstabler** [gregorbj/VisionEval#28]
potentially turn off the GET and SET functions from doing all the data checks since they are cumbersome and slow.  Related to #23.

**Comment by gregorbj** [comment]
The "writeToTable" function has been modified to eliminate the checking of data to be written against the specification. This now places the responsibility on assuring that data meets specs on the module. Modules will need to include guards to assure that their outputs conform to specifications. For example, they will need to assure that they do not return any NA or NaN values. All other checks on data consistency are made based on comparing specifications which is a fast process. Initialization functions have been added which check all of the Inp, Get, and Set specifications for all the modules that are called by a model run script to check whether all data specifications are consistent before the model is run. This is in a development branch that has not yet been added to the repo.

**Comment by gregorbj** [comment]
All the data checks have been moved to the model initialization step. The framework simulates all of the transactions with the datastore that will occur when the model runs and determines whether the data that a module will need when it runs will be present in the datastore at that time and whether the data attributes are correct. Data checking in lower level functions has been removed.
