### ISSUE TITLE
allow the NAME argument to INP, GET, SET to be a vector of column names

### ISSUE THREAD

**Issue by bstabler** [gregorbj/VisionEval#29]
In the short term, allow the NAME argument to INP, GET, SET to be a vector of column names that share the same data type, etc.  This will make specifying the data list much easier.

In the long term, potentially automatically generate the list with code, maybe even the testing code.

**Comment by gregorbj** [comment]
The specifications for Inp, Get and Set now allow a list of column (dataset) names to be specified in the NAME attribute when all the columns share the same attribute values. For example the following input specification lists 3 items:
    item(
      NAME =
        items("Metropolitan",
              "Town",
              "Rural"),
      FILE = "devtype_proportions.csv",
      TABLE = "Azone",
      GROUP = "Year",
      . . .
    )
A new "processModuleSpecs" utility function has been added which converts multiple item specifications to individual item specifications. This is in a development branch that has not yet been added to the repo.

**Comment by gregorbj** [comment]
This is implemented in the latest development branch.
