### ISSUE TITLE
add a parameters.csv/json file to the inputs folder

### ISSUE THREAD

**Issue by bstabler** [gregorbj/VisionEval#30]
add a parameters.csv/json file to the inputs folder and read it into the data store.  This is for scenario settings since the existing parameters.json for is model setup/configuration, not scenarios inputs.

**Comment by gregorbj** [comment]
Renamed the "parameters.json" file in the "defs" directory of the model to be "run_parameters.json". This file contains information about the model run as before. Added a "Model" parameter to this file to use for identifying the model name (e.g. RPAT, RSPM, EERPAT, GreenSTEP). Added a "model_parameters.json" file to the "defs" directory. This file defines all the model parameters that have been defined in the "global_values.txt" file that is in the model directory for the GreenSTEP, RSPM, etc. models. A "loadModelParameters" function which is called by the "initializeModel" function reads the "model_parameters.json" file and saves them in a "Model" table in the "Global" group. To access the values of any of these parameters, a module will need to include a Get specification for the parameter.

**Comment by gregorbj** [comment]
Note on previous comment. This has been done in a development branch and is not yet committed to the repo.

**Comment by gregorbj** [comment]
This is implemented in the latest development branch.
