### ISSUE TITLE
improve the handling of years

### ISSUE THREAD

**Issue by bstabler** [gregorbj/VisionEval#31]
improve the handling of years since modules needs to be able to INP, GET, SET different years of data, including Global.  [SynFirms](https://github.com/RSGInc/VisionEvalSyntheticFirms) for example gets Global data for the base year run and base year data for future year runs.  This can't be done right now.

We talked about a couple solutions:
  - RunModule having an INP_YEAR and SET_YEAR
  - the INP, GET, SET list having a YEAR for each data item.

We also talked about tokens in the INP, GET, SET entries such as {BaseYear}, {CurrentYear}, etc.   

related #15

**Comment by gregorbj** [comment]
Adding a new GROUP attribute to Inp, Get, and Set specifications. Allowable attribute values are "Global", "BaseYear" and "Year". Code for reading to and writing from datastore uses this attribute to determine what group to read from or write to. If "Global", it addresses the Global group. If "BaseYear", it addresses the year group identified as the base year in the model parameters (e.g. "2010"). If "Year", it addresses the year group for the year the model is running for. These changes are being made in a development branch that has not been added to the repo yet.

**Comment by gregorbj** [comment]
The latest development version implements the "GROUP" specification. In addition, when the "runModule" function prepares the data list to pass to the module, it includes the model state in the list. It also includes global model parameters that are specified in the "Get" specification. A new "model_parameters.json" file is added to the "defs" directory for a model that is used to specify global model parameters. The "initializeModel" function saves the parameters in the "Global/Model" group of the datastore.
