### ISSUE TITLE
merge all VE repos back into the master

### ISSUE THREAD

**Issue by bstabler** [gregorbj/VisionEval#42]
To centralize development and maintenance, including issue tracking, milestones, and the wiki for project management, we're bringing these projects back into the master project and re-arranging things a bit:

https://github.com/RSGInc/VisionEvalRPAT

https://github.com/RSGInc/VisionEvalSyntheticFirms

https://github.com/gregorbj/SimHouseholds

And then delete these repos and update the [VE wiki](https://github.com/gregorbj/VisionEval/wiki) as well

**Comment by bstabler** [comment]
And delete old repos

**Comment by bstabler** [comment]
@gregorbj - please delete the gregorbj/SimHouseholds repo since it is now [here](https://github.com/gregorbj/VisionEval/tree/master/sources/modules/VESimHouseholds)

**Comment by gregorbj** [comment]
Merged the VERSPM repo (was RSPM_VisionEval) and deleted the RSPM_VisionEval repo. Deleted the SimHouseholds repo. All repos now merged and old repos removed.
