### ISSUE TITLE
eventually transfer site to new organization

### ISSUE THREAD

**Issue by bstabler** [gregorbj/VisionEval#44]
transfer to https://github.com/VisionEval

**Comment by bstabler** [comment]
This is now in the [Roadmap](https://github.com/gregorbj/VisionEval/wiki/Development-Roadmap#new-ve-home)

**Comment by bstabler** [comment]
This will be done after the Pooled Funds is setup.  For now, https://github.com/VisionEval/VisionEval is a static fork.

**Comment by jrawbits** [comment]
We have forked the repository and will be pulling updates from your repository over the next few weeks (up until the procurement freeze).
