### ISSUE TITLE
Unified treatment of geographic areas and naming of geographic levels

### ISSUE THREAD

**Issue by gregorbj** [gregorbj/VisionEval#5]
One of the objectives of the RSPM framework is to make the statewide and metropolitan models more consistent with how they treat geographic units. The statewide model divides space into counties (or similar divisions such as PUMAs) and metropolitan areas. The metropolitan model divides space into metropolitan divisions and the divisions into districts (which now roughly correspond to census tracts, but could in the future correspond to block groups). In the  RSPM framework there would be "divisions" and "districts" for both the statewide and metropolitan implementations. However, while divisions would be explicit geographic units in all implementations (i.e. some inputs would be specified by division), districts could be implicit just as the assignment of land use characteristics to households in the GreenSTEP and EERPAT models is implicit. In these models, density and urban mixed-use characteristics don't represent actual places within a metropolitan area, instead they represent distributions of characteristics that are likely to exist within the metropolitan area. Household land use attributes are selected from these distributions. The new model would include functions which synthesize districts and their land use characteristics when they are not explicitly defined. Doing this will enable all the models to use the same functions for associating households with land use characteristics such as density, place type and building type. I'm looking for input on this approach and for the naming of geographic units. If we follow the current RSPM naming convention, the larger units are called 'divisions' and the smaller units are called 'districts'. Districts nest within divisions. Districts also nest within metropolitan areas, but divisions may or may not nest within metropolitan areas.

**Comment by abigazzi** [comment]
The terms division and district seem intuitive to me. But I'm a little unclear on how rural counties/divisions would work - could the entire division be one district? 

Are divisions mutually exclusive and exhaustive of the modeled geography?

**Comment by gregorbj** [comment]
Yes, divisions are mutually exclusive. I would see rural counties being one division. A metropolitan county could be split into several divisions and it could be desirable to do so, but it could also be one division. I need to think about districts in the context of rural counties more. I could see districts in rural counties being used to partition households in urban areas within the county (e.g. The Dalles, Madras, Pendleton) from households located in rural areas of the county.

**Comment by bstabler** [comment]
I would actually prefer to use ZONE for the smallest spatial unit and DISTRICT for the aggregation of zones since this is consistent with travel models.  A ZONE can be used for any type of geography - TAZ, tract, county, etc, and a DISTRICT is a group of ZONEs.

**Comment by mrspeel** [comment]
Per 7/31 Milestone Call, the decision was made to use "NAZ (Neighborhood Analysis Zone)" or similar named unit as the fundamental building block geography, and "Districts" would be aggregations of NAZs.  NAZ was preferred over "Zone" as this forces people to not equate the NAZ with traditional travel model TAZs, but to think of them as larger geographic areas consistent with the strategic nature of the RSPM model and the census tract estimation of the model. It also drops the "Division" term which has less obvious implications on its aggregation level. 

The preferred name for the building block "NAZ" is still being considered. "Places" was suggested but discounted as it might be confused with the census terminology.
