### ISSUE TITLE
Test code for the framework is broken and incomplete

### ISSUE THREAD

**Issue by jrawbits** [gregorbj/VisionEval#51]
Some strategy for developing and including unit and system tests should be put in place.  Existing tests within the VisionEval Framework do not currently (2017-03-02) appear to run.  Basic tests for comprehensive framework API functionality are desirable for several operational reasons:  (1) to ensure that all functionality works as intended; (2) to ensure that updates to the API have not broken other expectations (e.g. some tests may involve functionality that was not directly modified); (3) the git history of the tests themselves will provide concrete examples to module and model developers of what they might have to change in their code to get it up to date with the new framework version. 

It is okay to have, say, VERPAT or the GUI-Visualizer act as a test harness (those obviously should be kept working), but it is important to have as comprehensive a set of unit tests as possible, and to organize them into a test suite to permit easy and automatic regression testing when changes are made.  Note that this is also a process request for the developers, not just a request for specific test code.

Specifically, I can’t run test script for the framework (in the “tests/data” directory).  I attempted to do that by loading the VisionEval R project into a fresh RStudio session, navigating to “data/tests”, and sourcing the “run_model.R” script.  I get this fatal error:
“Error in initializeModel(Dir = "defs", ParamFile = "parameters.json",  : 
  unused arguments (Dir = "defs", ParamFile = "parameters.json")”

**Comment by bstabler** [comment]
major improvements for testing in pull request #104
