### ISSUE TITLE
call to processModuleInputs has too many parameters

### ISSUE THREAD

**Issue by PeterVermont** [gregorbj/VisionEval#56]
visioneval.R line 81:

![image](https://cloud.githubusercontent.com/assets/889233/23871061/3c8537f8-07ff-11e7-9dd8-3b7f01ec70c7.png)

**Comment by gregorbj** [comment]
The call to 'processModuleInputs' is no longer in the 'runModule' function. This was there before the 'initializeModel' function was complete. Now all input processing occurs with model initialization.
