### ISSUE TITLE
Do not require working directory to be set to run_model.R directory

### ISSUE THREAD

**Issue by PeterVermont** [gregorbj/VisionEval#57]
visioneval assumes that relative paths in the run_model.R script are relative to the current working directory (e.g. ParamDir = "defs"). Instead I think it makes sense to treat them as relative to the script's location.

Requiring the user to set a specific working directory before running a package seems incorrect to me.

**Comment by bstabler** [comment]
@gregorbj - is this done?  Can we close this?

**Comment by gregorbj** [comment]
This is implemented. The user specifies the relative path name of the datastore in the 'DatastoreName' parameter of the 'run_parameters.json' file.
