### ISSUE TITLE
Any value in standardizing names for outputs?

### ISSUE THREAD

**Issue by gregorbj** [gregorbj/VisionEval#7]
Do you think there is any value in standardizing names for outputs? Is there any value in standardizing abbreviations for output names? For example, should household size data always be saved as HhSize in the data store? One potential value is that standard abbreviations and names would make code more readable. For example, seeing 'Hh' in an object name such as 'HhIncome' would make it clear that the data object stores household income data. Another possible advantage is that module code would be less likely to break or need to be changed when it uses outputs from a new module. For example, what if a travel prediction module uses data named 'HhIncome' produced by another module which predicts household income, but then a developer comes along who creates a better household income model but calls the result 'HhInc' instead. The travel prediction module would not be able to use the results of the new household income module without rewriting the travel prediction module.

**Comment by jrawbits** [comment]
I’d suggest developing and using internal naming conventions<https://en.wikipedia.org/wiki/Naming_convention_%28programming%29> (not standards) for the core modules in RSPM (i.e. all the modules invented here).

The NMTK approach to file inputs is to force the user to map their input fields onto the names chosen internally by the tool (module) developer when they set up a job for the tool.  A similar strategy is used in Microsoft Excel and elsewhere to reconcile divergent names.  If you’re not already contemplating such a thing, I’d suggest implementing a simple mapping facility that enables someone who is trying to “feed” a module with a pre-built data source to provide an optional table of name conversions (two columns, “From” and “To”) and for any name not found in “From” (or if the entire table is not supplied), just pass the names through unaltered and hope for the best (but of course generate errors if required fields are missing, and generate lightweight warnings if a field is passed through but not used).

**Comment by bstabler** [comment]
I agree with @jrawbits.  I think a convention / recommendation is a good idea, but I'm hesitant to require/enforce a standard.  It is a bad idea to write any code based on what an object/output is called.  The object/output metadata should tell you what the object is, not its name.
