### ISSUE TITLE
VERPAT has DESCRIPTION and NAMESPACE file but is not meant to be a package and fails if you try

### ISSUE THREAD

**Issue by PeterVermont** [gregorbj/VisionEval#70]
Suggest these get deleted since their presence enables the 'build' options in RSTUDIO and they fail because run_model.R is not in the expected directory 'R'

**Comment by gregorbj** [comment]
I merged the change with a comment that we should discuss whether VERPAT should be a package or not. I think you're right, it should not be a package. If it was a package, that would complicate the process for the user to add model input files or change parameter files, so I think that it shouldn't become a package.

**Comment by PeterVermont** [comment]
I was just following your lead on VERSPM which I figured represented your current thinking. Plus VERPAT documentation could not be build because collate of run_model.R failed (maybe because it was not in an ‘R’ subdirectory?)

……………………………………………..
PETER ANDREWS
Senior Software Engineer

RSG
55 Railroad Row | White River Junction, VT 05001
o 802.359.6411 | m 802.356.3141
www.rsginc.com<http://www.rsginc.com/>
……………………………………………..

**Comment by gregorbj** [comment]
The current approach makes sense to me. The structure is simple and easy to understand. If it was an R package, the structure would be more complicated. I don't see an advantage of changing the structure, but I want to make sure I'm not missing something.
