### ISSUE TITLE
Warning messages: 1: In is.na(Data_) :   is.na() applied to non-(list or vector) of type 'NULL'

### ISSUE THREAD

**Issue by PeterVermont** [gregorbj/VisionEval#73]
> source('~/dev/VisionEval/sources/models/VERPAT/run_model.R')
[1] "2017-03-28 16:12:48 -- Initializing Model."
[1] "2017-03-28 16:13:03 -- Model successfully initialized."
[1] "2017-03-28 16:13:03 -- Starting module 'CreateBaseSyntheticFirms' for year '2005'."
[1] "2017-03-28 16:13:07 -- Finish module 'CreateBaseSyntheticFirms' for year '2005'."
[1] "2017-03-28 16:13:07 -- Starting module 'CreateFutureSyntheticFirms' for year '2010'."
[1] "2017-03-28 16:13:10 -- Finish module 'CreateFutureSyntheticFirms' for year '2010'."
Warning messages:
1: In is.na(Data_) :
  is.na() applied to non-(list or vector) of type 'NULL'
2: In is.na(Data_) :
  is.na() applied to non-(list or vector) of type 'NULL'
> 

![image](https://cloud.githubusercontent.com/assets/889233/24426690/62340f28-13d6-11e7-8e75-9459b9245501.png)

**Comment by PeterVermont** [comment]
More information:

![image](https://cloud.githubusercontent.com/assets/889233/24427184/0e02dc48-13d8-11e7-857c-1785f5f857b5.png)

**Comment by gregorbj** [comment]
I don't get these warnings when I run VERPAT.

**Comment by PeterVermont** [comment]
Did you try deleing the Datastore.h5 and (not sure if it matters) the ModelState.Rda? before the run and the ‘restarting R’?
……………………………………………..
PETER ANDREWS
Senior Software Engineer

RSG
55 Railroad Row | White River Junction, VT 05001
o 802.359.6411 | m 802.356.3141
www.rsginc.com<http://www.rsginc.com/>
……………………………………………..

**Comment by gregorbj** [comment]
Yes. Started clean. Can't replicate the error. One thing I've found in the past is that rebuilding a package doesn't seem to always replace everything in an installed package so I'll delete the package from my R directory and then rebuild. Just to make sure that the error wasn't hidden because my packages weren't consistent with the master, I deleted visioneval and VESyntheticFirms and rebuilt. Then I ran VERPAT. No errors.

**Comment by PeterVermont** [comment]
Are you on a Mac? I just tried it on my wife's MacBook and also did not get the error.

One of the differences between *nix and Windows is that the Windows filesystem is case sensitive. If this is a OS specific then my guess is we have a case issue. I grepped for case issues with Business, Year, and naics (the three fields mentioned above) but did not see any problems.

[HDf5 is also case sensitive](https://www.harrisgeospatial.com/docs/h5_list.html) but conceivably that could vary by implementation to match the filesystem convention...

**Comment by gregorbj** [comment]
I'm using Windows 10.

**Comment by PeterVermont** [comment]
Commit 61537cfaad921b4d90b8f5a56b41e683de592965 adding CreateBaseSyntheticFirmsSpecifications.rda seems to have fixed this issue. I don't understand exactly why it makes a difference but I can see that the .rda file has changed:

![image](https://cloud.githubusercontent.com/assets/889233/24459305/34311632-1469-11e7-9f0f-abca0900937a.png)
