### ISSUE TITLE
parseModelScript throws unhelpful errors

### ISSUE THREAD

**Issue by PeterVermont** [gregorbj/VisionEval#78]
The errors are opaque...

...for when a file does not exist....

> Browse[1]> visioneval::parseModelScript('nonexistent.R', TestMode = TRUE)
> Error during wrapup: cannot open the connection

...and for when a file does not have the expected content....

> Browse[1]> visioneval::parseModelScript('emptyFile.R', TestMode = TRUE)
> Error during wrapup: missing value where TRUE/FALSE needed

This is not a big deal as I can work with it.

**Comment by gregorbj** [comment]
parseModelScript function now checks whether the specified script exists and whether the script includes any 'runModule' function calls. Gives useful error messages.
