### ISSUE TITLE
Make arguments to initializeModel parameters in run_parameters.json

### ISSUE THREAD

**Issue by gregorbj** [gregorbj/VisionEval#79]
GUI implementation would benefit from being able to read the arguments of the 'initializeModel' function call. This could be achieved by making the arguments to be parameters of the 'run_parameters.json' file instead. Then the GUI code could read the parameters from that file. The 'initializeModel' function call would get the arguments from the file as well. In addition, the 'initializeModel' function can be simplified to eliminate the 'ParamDir', 'RunParamFile', 'GeoFile', and 'ModelParamFile' arguments and replacing them with hard-coded values. Allowing users to specify values adds no benefit to the user and adds the potential for confusion in setting up a model.

**Comment by bstabler** [comment]
we don't need this anymore since the GUI is parsing and understanding the run script on its own now.
