### ISSUE TITLE
Storing additional types of data in datastore

### ISSUE THREAD

**Issue by gregorbj** [gregorbj/VisionEval#8]
In addition to storing matrices, the Fast trips project is using HDF5 for storing other data as well - http://fast-trips.mtc.ca.gov/2015/08/21/standard-deviation/ (From Ben Stabler in email)

**Comment by gregorbj** [comment]
Would like to accommodate more types of data in the future, but I don't want to get bogged down with specifying too much now. I do think we need to accommodate matrices now because they are important to some of the improvements identified in ODOT's longer range work program such as specifying household employment location in relation to residence.

**Comment by bstabler** [comment]
the data store can store matrices, tables, and other data items
