### ISSUE TITLE
Include utility functions in visioneval package?

### ISSUE THREAD

**Issue by gregorbj** [gregorbj/VisionEval#83]
The GreenSTEP/RSPM code includes quite a bit of redundancy in methods. For example, a number of functions use a binary search algorithm. Incorporating functions to implement commonly used functions in the visioneval package could simplify module code.

**Comment by bstabler** [comment]
this makes sense to me.  I think the key issue right now would be the timing since we want to make sure we keep the project moving along.

**Comment by gregorbj** [comment]
Added utility functions for use by modules: binarySearch, makeModelFormulaString, applyBinomialModel, applyLinearModel. These are the functions that address most of the code duplication in RSPM/GreenSTEP.
