### ISSUE TITLE
Distribute required R packages with the framework

### ISSUE THREAD

**Issue by gregorbj** [gregorbj/VisionEval#9]
Distribute all the R packages required use the framework since finding and installing dependencies can be a real problem for uses. (Ben Stabler email comment)

**Comment by gregorbj** [comment]
I agree that we should package up all framework dependencies with the framework distribution.

**Comment by bstabler** [comment]
This is now handled via R commands to download GitHub packages and install them.  See [README](https://github.com/gregorbj/VisionEval/blob/master/README.md) for an example.
